image: 
  - Visual Studio 2015
  - Ubuntu

only_commits:
  message: /BUILD_RELEASE/

skip_commits:
  author: /John|Jack/


environment:
  # these variables are common to all jobs
  BUILD_OWNER: hernad
  # disable powershell on linux
  APPVEYOR_YML_DISABLE_PS_LINUX: true

  matrix:
  # - MSYS2_ARCH: x86_64
  #   MSYSTEM: MINGW64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    MSYS2_ARCH: i686
    MSYSTEM: MINGW32
    BUILD_ARTIFACT: windows_x86

  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    BUILD_ARTIFACT: linux_x86

platform:
  - x86

configuration:
  - Release


#before_build:
#- set Path=%CD%\%MINGW_DIR%\bin;%Path%
#- echo %PATH%
#- dir %MINGW_DIR%
#- g++ --version
#- mingw32-make --version

#build_script:
#- mkdir build
#- cd build
#- if [%COMPILER%]==[MinGW] echo "hello world"
#- if [%COMPILER%]==[MinGW] gcc --version
#- if [%COMPILER%]==[MinGW-w64] cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=C:\mingw64 -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..

build_script:
- cmd: '%APPVEYOR_BUILD_FOLDER%\appveyor.bat'

- sh: '${APPVEYOR_BUILD_FOLDER}/appveyor.sh'

on_success:
#- cmd: cd C:\
- cmd: if [%BUILD_TYPE%]==[Release] echo "SUCCESS"
- sh: echo "Ubuntu sucess :)"

#matrix:
#  fast_finish: true

# deploy: off


artifacts: 
  # relative to build folder
  - path: hello_$(BUILD_ARTIFACT)_$(APPVEYOR_REPO_TAG_NAME).zip


deploy:
- provider: BinTray
  name: bintray hernad windows
  username: hernad
  subject: hernad
  repo: appveyor
  package: hello-windows-x86
  version: '$(APPVEYOR_REPO_TAG_NAME)'
  #artifact: 'hello_windows_x86_$(APPVEYOR_REPO_TAG_NAME).zip'
  api_key:
    secure: CmTociD4LaDugZgY8k5Esn0tcA1nGvV583hTrbUGmGrnBtb6B1xyArOBmFzN5TjTLuRrfB9kBNiYtqyhBf0v2HZE8uKm2cl8zGoYTU8Afb0=
  publish: true
  override: true
  #explode: true
  on:
    appveyor_repo_tag: true
    BUILD_ARTIFACT: windows_x86

- provider: BinTray
  name: bintray hernad ubuntu
  username: hernad
  subject: hernad
  repo: appveyor
  package: hello-linux-x86
  version: '$(APPVEYOR_REPO_TAG_NAME)'
  #artifact: 'hello_linux_x86_$(APPVEYOR_REPO_TAG_NAME).zip'
  api_key:
    secure: CmTociD4LaDugZgY8k5Esn0tcA1nGvV583hTrbUGmGrnBtb6B1xyArOBmFzN5TjTLuRrfB9kBNiYtqyhBf0v2HZE8uKm2cl8zGoYTU8Afb0=
  publish: true
  override: true
  #explode: true
  on:
    appveyor_repo_tag: true
    BUILD_ARTIFACT: linux_x86