image: 
  - Visual Studio 2015
  - Ubuntu

only_commits:
  message: /BUILD_RELEASE/

skip_commits:
  author: /John|Jack/

# https://www.appveyor.com/docs/environment-variables/
# https://github.com/scivision/pymap3d/blob/master/.appveyor.yml
# https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/ - CI_WINDOWS, CI_LINUX 
# https://stefanscherer.github.io/setup-windows-docker-ci-appveyor/
# http://conan-docs.readthedocs.io/en/feature-cmake-toolchain-file/integrations/appveyor.html

environment:
  # these variables are common to all jobs
  BUILD_OWNER: hernad

  matrix:
  # - MSYS2_ARCH: x86_64
  #   MSYSTEM: MINGW64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    MSYS2_ARCH: i686
    MSYSTEM: MINGW32
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

platform:
  - x86

configuration:
  - Release


#before_build:
#- set Path=%CD%\%MINGW_DIR%\bin;%Path%
#- echo %PATH%
#- dir %MINGW_DIR%
#- g++ --version
#- mingw32-make --version

#build_script:
#- mkdir build
#- cd build
#- if [%COMPILER%]==[MinGW] echo "hello world"
#- if [%COMPILER%]==[MinGW] gcc --version
#- if [%COMPILER%]==[MinGW-w64] cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=C:\mingw64 -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..

build_script:
- cmd: '%APPVEYOR_BUILD_FOLDER%\appveyor.bat'

- sh: '%APPVEYOR_BUILD_FOLDER%\appveyor.sh'

on_success:
- cd C:\
- if [%BUILD_TYPE%]==[Release] echo "SUCCESS"


#matrix:
#  fast_finish: true

# deploy: off

#deploy:
#  - provider: Environment
#    name: production
#    on:
#      appveyor_repo_tag: true

artifacts: 
  # relative to build folder
  - path: hello_$(APPVEYOR_REPO_TAG_NAME).zip


deploy:
- provider: BinTray
  username: hernad
  subject: hernad
  repo: appveyor
  package: playground
  version: '$(APPVEYOR_REPO_TAG_NAME)'
  api_key:
    secure: CmTociD4LaDugZgY8k5Esn0tcA1nGvV583hTrbUGmGrnBtb6B1xyArOBmFzN5TjTLuRrfB9kBNiYtqyhBf0v2HZE8uKm2cl8zGoYTU8Afb0=
  publish: true
  override: true
  #explode: true
  on:
    appveyor_repo_tag: true