image: Visual Studio 2015


environment:
  # these variables are common to all jobs
  BUILD_OWNER: hernad

  matrix:
  # - MSYS2_ARCH: x86_64
  #   MSYSTEM: MINGW64
  - MSYS2_ARCH: i686
    MSYSTEM: MINGW32

platform:
  - x86

configuration:
  - Release


#before_build:
#- set Path=%CD%\%MINGW_DIR%\bin;%Path%
#- echo %PATH%
#- dir %MINGW_DIR%
#- g++ --version
#- mingw32-make --version

#build_script:
#- mkdir build
#- cd build
#- if [%COMPILER%]==[MinGW] echo "hello world"
#- if [%COMPILER%]==[MinGW] gcc --version
#- if [%COMPILER%]==[MinGW-w64] cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=C:\mingw64 -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..

build_script:
- '%APPVEYOR_BUILD_FOLDER%\appveyor.bat'

on_success:
- cd C:\
- if [%BUILD_TYPE%]==[Release] echo "SUCCESS"


#matrix:
#  fast_finish: true

# deploy: off

#deploy:
#  - provider: Environment
#    name: production
#    on:
#      appveyor_repo_tag: true

artifacts: 
  # relative to build folder
  - path: hello.zip
    name: hello

deploy:
- provider: BinTray
  username: hernad
  subject: hernad
  repo: appveyor
  package: playground
  #version: version
  publish: true
  override: true
  #explode: true

